#!/bin/bash

# checking if enviromental variables set properly
if [ -z "$PGLD_PATH" ]
then
    echo "Please export PGLD_PATH according to README.md" 
    exit
fi  

if ! [[ $PATH = *""$PGLD_PATH"/script/"* ]] || ! [[ $PATH == *""$PGLD_PATH"/script/test_stand/"* ]]; then
    echo "Please export PATH according to README.md"
    exit
fi

source $PGLD_PATH/config/pg_leader.config

ID=$1

if [ -z "$ID" ]; then
    echo "Please enter the ID of the node."
    exit
fi

DBNAME="$PGLD_DB_PATHNAME_TEMPLATE"$ID
if [[ !(-d "$DBNAME") ]]; then
    echo "$DBNAME is not created. initdb it? (y/n):"
    read confirm
    confirm=${confirm,,}

    if [[ "$confirm" == "y" ]]; then
        initdb -D "$DBNAME"
        echo "$DBNAME database cluster CREATED."
    elif [[ "$confirm" == "n" ]]; then
        echo Exit
        exit
    else
        echo Unknown answer, use 'y' or 'n'
        exit
    fi

else
    echo "$DBNAME database cluster EXISTS."
fi

PORT=$(($PGLD_START_PORT + $ID))

postgres -D "$PGLD_DB_PATHNAME_TEMPLATE"$ID                                                               \
             -c shared_preload_libraries=$EXTENSION_NAME                                                  \
             -c pg_leader.node_id=$ID                                                                     \
             -c pg_leader.n_nodes=$N_NODES                                                                \
             -c pg_leader.cluster_conf="$IPv4_CLUSTER"                                                    \
             -c pg_leader.min_timeout=$MIN_TIMEOUT                                                        \
             -c pg_leader.max_timeout=$MAX_TIMEOUT                                                        \
             -c pg_leader.heartbeat_timeout=$HEARTBEAT_TIMEOUT                                            \
             -c pg_leader.enable_log=$ENABLE_LOG                                                          \
             -c pg_leader.log_file=$LOG_NAME                                                              \
             -p $PORT
